seed_everything: 3841570033
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 16 
  min_epochs: 2 
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 0.03
  limit_val_batches: 0.03
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: true
  enable_progress_bar: true 
  enable_model_summary: true 
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  satellite_resolution:
  - 400
  - 400
  drops_UAV:
    dropout: 0.1
    attn_drop: 0.1
    proj_drop: 0.1
    head_drop: 0.1
    mlp_drop1: 0.1
    mlp_drop2: 0.1
    pos_drops: 0.05
  drops_satellite:
    dropout: 0.1
    attn_drop: 0.1
    proj_drop: 0.1
    head_drop: 0.1
    mlp_drop1: 0.1
    mlp_drop2: 0.1
    pos_drops: 0.05
  fusion_dropout: 0.1
  pretrained_twins: true
  lr_backbone: 0.01
  lr_fusion: 0.01
  milestones:
  - 2
  - 4
  - 6
  - 8
  gamma: 0.2
data:
  uav_dataset_dir: "/home/spagnologasper/Documents/uav-localization-experiments/drone_dataset"
  satellite_dataset_dir: "/home/spagnologasper/Documents/uav-localization-experiments/satellite_dataset"
  sat_zoom_level: 16
  uav_patch_width: 128
  uav_patch_height: 128
  heatmap_kernel_size: 33
  test_from_train_ratio: 0.1
  uav_scales:
  - 3.0
  transform_mean:
  - 0.485
  - 0.456
  - 0.406
  transform_std:
  - 0.229
  - 0.224
  - 0.225
